# Ubuntu 20.04 ???
#ARG BASE_IMAGE=nvcr.io/nvidia/cuda:12.1.0-cudnn8-devel-ubuntu22.04
ARG PYTHON_VERSION=3.10.12
ARG PYTORCH_VERSION=2.3.0
ARG MAX_JOBS=4
ARG APEX_COMMIT=810ffae374a2b9cb4b5c5e28eaeca7d7998fca0c
ARG TE_COMMIT=7d576ed25266a17a7b651f2c12e8498f67e0baea
ARG NEMO_RUN_TAG=34259bd3e752fef94045a9a019e4aaf62bd11ce2
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#FROM ${BASE_IMAGE} AS python_base
FROM nvcr.io/nvidia/cuda:12.1.1-cudnn8-devel-ubuntu20.04 as python_base
ARG PYTHON_VERSION
ARG MAX_JOBS
ENV MAX_JOBS=${MAX_JOBS}

#RUN --mount=type=cache,id=apt-cache,target=/var/cache/apt,sharing=locked \
#    --mount=type=cache,id=apt-lib,target=/var/lib/apt,sharing=locked \
#    <<EOF
#apt update -y
#apt upgrade -y
#apt-get install -qyy \
#    -o APT::Install-Recommends=false \
#    -o APT::Install-Suggests=false \
#    curl \
#    build-essential \
#    ca-certificates \
#    curl \
#    software-properties-common \
#    git \
#    ninja-build \
#    cmake \
#    openmpi-bin \
#    libopenmpi-dev \
#    checkinstall \
#    libreadline-gplv2-dev \
#    libncursesw5-dev \
#    libssl-dev \
#    libsqlite3-dev \
#    tk-dev \
#    libgdbm-dev \
#    libc6-dev \
#    libbz2-dev \
#    libffi-dev \
#    zlib1g-dev
#rm -rf /var/lib/apt/lists/*
#EOF

RUN apt update -y && apt upgrade -y && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    -o APT::Install-Recommends=false \
    -o APT::Install-Suggests=false \
    build-essential \
    ca-certificates \
    curl \
    software-properties-common \
    git \
    ninja-build \
    cmake \
    openmpi-bin \
    libopenmpi-dev \
    checkinstall \
    libreadline-dev \
    libncursesw5-dev \
    libssl-dev \
    libsqlite3-dev \
    tk-dev \
    libgdbm-dev \
    libc6-dev \
    libbz2-dev \
    libffi-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build/python
RUN <<EOF
curl -O https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz
tar -zxf Python-${PYTHON_VERSION}.tgz
cd Python-${PYTHON_VERSION}
./configure --enable-optimizations --prefix=/usr
make install
ln -s /usr/bin/python3 /usr/bin/python

python -m ensurepip --upgrade
ln -s /usr/bin/pip3 /usr/bin/pip
EOF

#COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
#
## - Silence uv complaining about not being able to use hard links,
## - tell uv to byte-compile packages for faster application startups,
## - prevent uv from accidentally downloading isolated Python builds,
## - pick a Python,
## - and finally declare `/venv` as the target for `uv sync`.
#ENV UV_LINK_MODE=copy \
#    UV_COMPILE_BYTECODE=1 \
#    UV_PYTHON=python3.10 \
#    UV_PYTHON_DOWNLOADS=never \
#    UV_PROJECT_ENVIRONMENT=/venv
#
#

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
FROM python_base AS pytorch_base
ARG PYTORCH_VERSION
ARG MAX_JOBS
ENV MAX_JOBS=${MAX_JOBS}
ENV CUDA_HOME="/usr/local/cuda-12.1"
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_REQUIRE_CUDA=cuda>=9.0
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
ENV CUDA_ARCH_LIST="75-real;80-real;86-real;89-real;90-real"
ENV TORCH_CUDA_ARCH_LIST="7.0 7.2 7.5 8.0 8.6 8.7 8.9 9.0 9.0a"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
#ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64
#ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:$PATH
#ENV LD_LIBRARY_PATH="/usr/local/lib/python3.10/dist-packages/torch/lib:/usr/local/lib/python3.10/dist-packages/torch_tensorrt/lib:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}"

WORKDIR /build/
# the --index-url **MUST MATCH** the base image CUDA version !!!
# maybe --no-build-isolation ??
RUN pip install --index-url https://download.pytorch.org/whl/cu121 torch==${PYTORCH_VERSION}


FROM pytorch_base AS dl_deps_base
ARG APEX_COMMIT
ARG TE_COMMIT
ARG NEMO_RUN_TAG
# NOTE:
# look at: https://github.com/pytorch/pytorch/blob/main/Dockerfile
# look at: https://github.com/huggingface/text-generation-inference/blob/main/Dockerfile

# See NeMo readme for the latest tested versions of these libraries
RUN git clone https://github.com/NVIDIA/apex.git && \
  cd apex && \
  git checkout ${APEX_COMMIT} && \
  pip install wheel -r requirements.txt && \
  pip install . -v --no-build-isolation --disable-pip-version-check --no-cache-dir \
  --config-settings "--build-option=--cpp_ext --cuda_ext --fast_layer_norm --distributed_adam --deprecated_fused_adam --group_norm"

# Transformer Engine pre-1.7.0. 1.7 standardizes the meaning of bits in the attention mask to match
RUN git clone https://github.com/NVIDIA/TransformerEngine.git && \
  cd TransformerEngine && \
  git fetch origin ${TE_COMMIT} && \
  git checkout FETCH_HEAD && \
  git submodule init && git submodule update && \
  NVTE_FRAMEWORK=pytorch NVTE_WITH_USERBUFFERS=1 MPI_HOME=/usr/local/mpi pip install . \

# Check the nemo dependency for causal conv1d and make sure this checkout
# tag matches. If not, update the tag in the following line.
RUN CAUSAL_CONV1D_FORCE_BUILD=TRUE pip --disable-pip-version-check --no-cache-dir install \
  git+https://github.com/Dao-AILab/causal-conv1d.git@v1.2.0.post2 \

# Mamba dependancy installation
RUN pip --disable-pip-version-check --no-cache-dir install \
  git+https://github.com/state-spaces/mamba.git@v2.0.3

# needed to install nemo-run
RUN pip install hatchling

RUN pip install nemo_run@git+https://github.com/NVIDIA/NeMo-Run.git@${NEMO_RUN_TAG}

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
FROM dl_deps_base AS bionemo_base

WORKDIR /workspace/bionemo2

COPY ./ci/docker/clobber_dependencies_into_requirements_txt.sh /workspace/bionemo2/ci/docker/clobber_dependencies_into_requirements_txt.sh

# Install 3rd-party deps and bionemo submodules.
COPY ./3rdparty /workspace/bionemo2/3rdparty
COPY ./sub-packages /workspace/bionemo2/sub-packages

# Note, we need to mount the .git folder here so that setuptools-scm is able to fetch git tag for version.
RUN --mount=type=bind,source=./.git,target=./.git \
  --mount=type=bind,source=./requirements-test.txt,target=/requirements-test.txt \
  --mount=type=bind,source=./requirements-cve.txt,target=/requirements-cve.txt \
  <<EOF
set -eo pipefail

/workspace/bionemo2/ci/docker/clobber_dependencies_into_requirements_txt.sh

pip install --no-build-isolation -e \
  ./3rdparty/* \
  -r all_requirements.txt \
  -r /requirements-cve.txt \
  -r /requirements-test.txt

rm -rf /tmp/*

pip install --no-deps -e ./sub-packages/bionemo-*

EOF
